//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahlerNo2.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MahlerNo2Entities : DbContext
    {
        public MahlerNo2Entities()
            : base("name=MahlerNo2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BreakTime> BreakTimes { get; set; }
        public virtual DbSet<Emoticon> Emoticons { get; set; }
        public virtual DbSet<Shot> Shots { get; set; }
        public virtual DbSet<Speech> Speeches { get; set; }
    }
}
