//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahlerNo2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speech
    {
        public int SpeechId { get; set; }
        public string Text { get; set; }
    }
}
